server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /monitor-x7k9m2p4.html {
        try_files $uri =404;
    }
}
